# Generated by Django 3.2.13 on 2022-05-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_transaction_winning_cash_and_more'),
        ('crickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_player', models.BooleanField(default=False)),
                ('vc_player', models.BooleanField(default=False)),
                ('mom_player', models.BooleanField(default=False)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crickets.matchlist')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crickets.rosterpoints')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserTeam123',
        ),
    ]
