# Generated by Django 3.2.13 on 2022-05-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0003_userselectteam_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasypoints',
            name='pid',
            field=models.CharField(max_length=100),
        ),
    ]
