# Generated by Django 3.2.13 on 2022-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0007_alter_userselectteam_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterpoints',
            name='match_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userselectteam',
            name='match_id',
            field=models.CharField(max_length=100),
        ),
    ]
