# Generated by Django 3.2.13 on 2022-05-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0009_alter_matchlist_timeleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselectteam',
            name='user_team_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
