# Generated by Django 3.2.13 on 2022-05-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0010_userselectteam_user_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselectteam',
            name='user_team_id',
        ),
    ]
