# Generated by Django 3.2.13 on 2022-05-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0011_remove_userselectteam_user_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasypoints',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crickets.rosterpoints'),
        ),
    ]
