# Generated by Django 3.2.13 on 2022-05-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0012_alter_fantasypoints_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasypoints',
            name='pid',
            field=models.CharField(max_length=100),
        ),
    ]
