# Generated by Django 3.2.13 on 2022-05-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_transaction_winning_cash_and_more'),
        ('crickets', '0014_userselectteam_user_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselectteam',
            name='user_team_id',
        ),
        migrations.CreateModel(
            name='TeamPointsCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.user')),
            ],
        ),
        migrations.AddField(
            model_name='userselectteam',
            name='team',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='crickets.teampointscal'),
            preserve_default=False,
        ),
    ]
