# Generated by Django 3.2.13 on 2022-05-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0016_auto_20220520_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantacyLiveMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('short_title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('format_str', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('status_str', models.CharField(max_length=100)),
                ('status_note', models.CharField(max_length=100)),
                ('cid', models.CharField(max_length=100)),
                ('com_title', models.CharField(max_length=100)),
                ('com_abbr', models.CharField(max_length=100)),
                ('com_category', models.CharField(max_length=100)),
                ('com_status', models.CharField(max_length=100)),
                ('com_season', models.CharField(max_length=100)),
                ('com_datestart', models.CharField(max_length=100)),
                ('com_country', models.CharField(max_length=100)),
                ('teama_team_id', models.CharField(max_length=100)),
                ('teama_name', models.CharField(max_length=100)),
                ('teama_short_name', models.CharField(max_length=100)),
                ('teama_logo_url', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('teama_scores_full', models.CharField(max_length=100)),
                ('teama_scores', models.CharField(max_length=100)),
                ('teama_overs', models.CharField(max_length=100)),
                ('teamb_team_id', models.CharField(max_length=100)),
                ('teamb_name', models.CharField(max_length=100)),
                ('teamb_short_name', models.CharField(max_length=100)),
                ('teamb_logo_url', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('teamb_scores_full', models.CharField(max_length=100)),
                ('teamb_scores', models.CharField(max_length=100)),
                ('teamb_overs', models.CharField(max_length=100)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('result_str', models.CharField(blank=True, max_length=100, null=True)),
                ('win_margin', models.CharField(blank=True, max_length=100, null=True)),
                ('winning_team_id', models.CharField(blank=True, max_length=100, null=True)),
                ('toss_text', models.CharField(blank=True, max_length=100, null=True)),
                ('toss_winner', models.CharField(blank=True, max_length=100, null=True)),
                ('toss_decision', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
