# Generated by Django 3.2.13 on 2022-05-24 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_transaction_winning_cash_and_more'),
        ('crickets', '0017_fantacylivematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinContestlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_no', models.CharField(blank=True, max_length=100, null=True)),
                ('match_id', models.CharField(blank=True, max_length=100, null=True)),
                ('spots', models.IntegerField(blank=True, null=True)),
                ('entry_fee', models.IntegerField(blank=True, null=True)),
                ('price_pool', models.IntegerField(blank=True, null=True)),
                ('level', models.JSONField(blank=True, null=True)),
                ('no_of_team', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.user')),
            ],
        ),
    ]
