# Generated by Django 3.2.13 on 2022-05-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0018_joincontestlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='no_of_team',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
