# Generated by Django 3.2.13 on 2022-05-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_transaction_winning_cash_and_more'),
        ('crickets', '0019_auto_20220528_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='userid',
            new_name='match_id',
        ),
        migrations.AddField(
            model_name='contest',
            name='match_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crickets.teampointscal'),
        ),
        migrations.CreateModel(
            name='JoinContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crickets.contest')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crickets.teampointscal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.user')),
            ],
        ),
    ]
