# Generated by Django 3.2.13 on 2022-05-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_transaction_winning_cash_and_more'),
        ('crickets', '0020_auto_20220528_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.user'),
        ),
    ]
