# Generated by Django 3.2.13 on 2022-05-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0021_leaderboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='joincontest',
            name='match_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
