# Generated by Django 3.2.13 on 2022-05-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0023_alter_userselectteam_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselectteam',
            name='match_id',
            field=models.CharField(max_length=100),
        ),
    ]
