# Generated by Django 3.2.13 on 2022-05-28 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0025_alter_userselectteam_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crickets.matchlist'),
        ),
    ]
