# Generated by Django 3.2.13 on 2022-05-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0026_alter_leaderboard_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterpoints',
            name='playing11',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BotTeamPointsCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('wk', models.IntegerField(default=0)),
                ('all', models.IntegerField(default=0)),
                ('bat', models.IntegerField(default=0)),
                ('bowl', models.IntegerField(default=0)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crickets.bot')),
            ],
        ),
        migrations.CreateModel(
            name='BotSelectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100)),
                ('player_id', models.CharField(max_length=100)),
                ('c_player', models.BooleanField(default=False)),
                ('vc_player', models.BooleanField(default=False)),
                ('momt_player', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crickets.bot')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crickets.botteampointscal')),
            ],
        ),
    ]
