# Generated by Django 3.2.13 on 2022-05-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0027_auto_20220530_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampointscal',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
