# Generated by Django 3.2.13 on 2022-05-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crickets', '0028_teampointscal_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantacylivematch',
            name='teama_logo_url',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fantacylivematch',
            name='teamb_logo_url',
            field=models.CharField(max_length=500),
        ),
    ]
