# Generated by Django 4.0.3 on 2022-05-05 11:31

import cart.models
import cart.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Mobile incorrect.', regex='^\\+?1?\\d{9,15}$')])),
                ('otp', models.CharField(max_length=6)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.ImageField(blank=True, storage=cart.storage.OverwriteStorage(), upload_to=cart.models.content_file_name)),
                ('profile_id', models.IntegerField(default=0)),
                ('referral', models.CharField(blank=True, max_length=150, null=True)),
                ('otp_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=0, verbose_name='Total amount')),
                ('add_amount', models.FloatField(default=0, verbose_name='Add amount')),
                ('deposit_cash', models.FloatField(default=0, verbose_name='Full Add amount')),
                ('win_amount', models.FloatField(default=0)),
                ('winning_cash', models.FloatField(default=0)),
                ('withdraw_amount', models.FloatField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('total_bonus_amount', models.FloatField(default=0)),
                ('Bonus', models.FloatField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_mobile', to='cart.user')),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheels_index', models.CharField(blank=True, max_length=200, null=True)),
                ('wheels_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.user')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='UserReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=1, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.IntegerField(blank=True, default=None, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('referral_date', models.DateTimeField(blank=True, null=True)),
                ('referral_url', models.CharField(blank=True, max_length=500, null=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_referred_by_user', to='cart.user')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_referral_user', to='cart.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiontype', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('winning_cash', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('transaction_method', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.user')),
            ],
        ),
    ]
